### ISSUE TITLE
Сделать в КА1 псевдопланирование.

### ISSUE THREAD

**Issue by igorro82** [mushrooms-fb/Arkada#12]

**Comment by igorro82** [comment]
[Проект_БИТам_Планирование_отгрузок.docx](https://github.com/mushrooms-fb/Arkada/files/10392991/_._._.docx)

**Comment by SimonovAleksandr** [comment]
В тестовой базе (Srvr="S-8";Ref="KA_copy_Zavyalov_05092022") сделал внешнюю обработку по созданию 4х типов док-ов: 1. "Заказы месяц" 2. "Заказ день" (отклонение +-10%) 3. Комплектовочная ведомость (данные тянутся из Заказов Покупателей) 4. "Ежедневный отчет по отгрузке" (данные из РТиУ). Все 4 типа док-ов формируются за указанный период по каждой организации: А, АЭ, ИПБ (+ СП) и по складам: Основной склад Челябинск и Производство Юрюзань (+Регион-ТДА-Юрюзанский склад и УОП-ТДА-Юрюзанский склад)

Светлана Хрусловская: Александр, добрый день! я ухожу в отпуск с пятницы, эту задачу передала Екатерине Жаворонковой (+7 912 301 9905). Она скорее всего со следующей недели к ней приступит

**Comment by SimonovAleksandr** [comment]
Вернулись к задаче. Создали чат для обсуждения корректировок, со Светланой и Екатериной.

**Comment by SimonovAleksandr** [comment]
Обработка называется бит_Альтернативное планирование
в базе Srvr="S-8";Ref="KA_copy_Zavyalov_05092022"

Документы в конфигурации:
бит_ЗаказМесяц
бит_ЗаказДень
бит_КомплектовочнаяВедомость
бит_ЕжедневныйОтчетПоОтгрузке

07.04 Екатерина должна обсудить с МЛГ подробности по ТЗ

**Comment by igorro82** [comment]
Обещали к 12.04. обновить формулировку и условие задачи.

**Comment by igorro82** [comment]
[Проект_БИТам_Планирование_отгрузок 12042023.docx](https://github.com/mushrooms-fb/Arkada/files/11222076/_._._.12042023.docx)

**Comment by igorro82** [comment]
Сохранил доработки Саши в cf.накатил в KA_copy_Zavyalov_05092022 свежую копию рабочей КА.
Доработал в соответствии с замечаниями, отдал на тестирование Жаворонковой Екатерине.

**Comment by igorro82** [comment]
[Альтернативное_планирование_29_06_2023.docx](https://github.com/mushrooms-fb/Arkada/files/11913378/_._29_06_2023.docx)

**Comment by VladislavSvetlichnyi** [comment]
[Альтернативное_планирование_04_07_2023.docx](https://github.com/mushrooms-fb/Arkada/files/11944977/_._04_07_2023.docx)
